### PR TITLE
fix file format, add missing style name

### PR DESCRIPTION
**Pull request by ItsNickBarry**
Node seems unable to load a `json`file with a `js` extension.  However, it works find if the main file is named `index.json`.

Also, the name of the style "Munich Dunkel" was missing.  I've added it.

### CODE REVIEW

**Comment by Boo-urns** [comment]
Cheers @ItsNickBarry :beers:	I'll take a look this weekend I don't see how it would affect my projects. Only thing that would be needed is a bump of the package. I'm thinking a patch bump.

**Review by Boo-urns — APPROVED** [review]
Thanks again @ItsNickBarry! 🍻

**Comment by ItsNickBarry** [comment]
@Boo-urns Cheers.

Though I'm wondering how this was working for you before.  Are you using some sort of front-end compiler that's able to load the `js` file as `json`?

**Comment by Boo-urns** [comment]
@ItsNickBarry 	looks like I wasn't even importing it yet 😞

**Comment by Boo-urns** [comment]
Quick look json-loader looks promising but it's no longer needed because of this PR 🎉

**Pull request merged**
